@startmindmap

<style>
rootNode {
    LineColor blue
    BackgroundColor yellow
    HorizontalAlignment left
}
node {
    Padding 12
    Margin 20
    HorizontalAlignment left
    LineColor blue
}
leafNode {
    LineStyle 2
    LineColor red
    HorizontalAlignment left
}
arrow {
    LineStyle 2
    LineThickness 2
    LineColor black
}

</style>

title __ Backend group roadmap __\nData Management

* Data\nmanagement
 *_ Data Governance
 * Data architecture
 * Tools
 * Techniques
left side
** Data modeling
 * Metadata
  * Data Catalog
 * Data quality
  *_ Monitoring

@endmindmap
